endif()

if(WITH_VALGRIND_MEMCHECK)
	check_include_files(valgrind/memcheck.h HAVE_VALGRIND_MEMCHECK_H)
    check_include_files(valgrind/memcheck.h FREERDP_HAVE_VALGRIND_MEMCHECK_H)
else()
	unset(HAVE_VALGRIND_MEMCHECK_H CACHE)
    unset(FREERDP_HAVE_VALGRIND_MEMCHECK_H CACHE)
endif()

if(UNIX OR CYGWIN)
@@ -698,9 +698,9 @@ if(UNIX AND NOT ANDROID)
	find_feature(libsystemd ${WLOG_SYSTEMD_JOURNAL_FEATURE_TYPE} ${WLOG_SYSTEMD_JOURNAL_FEATURE_PURPOSE} ${WLOG_SYSTEMD_JOURNAL_FEATURE_DESCRIPTION})

	if(LIBSYSTEMD_FOUND)
		set(HAVE_JOURNALD_H TRUE)
        set(WINPR_HAVE_JOURNALD_H TRUE)
	else()
		unset(HAVE_JOURNALD_H)
        unset(WINPR_HAVE_JOURNALD_H)
	endif()
endif(UNIX AND NOT ANDROID)

@@ -969,7 +969,7 @@ endif()
set(FREERDP_BUILD_CONFIG_LIST "")
GET_CMAKE_PROPERTY(res VARIABLES)
FOREACH(var ${res})
		IF (var MATCHES "^WITH_*|^BUILD_TESTING|^HAVE_*")
    IF (var MATCHES "^WITH_*|^BUILD_TESTING|^WINPR_HAVE_*")
				LIST(APPEND FREERDP_BUILD_CONFIG_LIST "${var}=${${var}}")
		ENDIF()
ENDFOREACH()
